version: "3.9"
services:
  node:
    image: pstramecki/node:latest
    build:
      dockerfile: .docker/node/Dockerfile
      context: .
      tags:
        - pstramecki/node:1.0.0
    env_file: ./.env
    tty: true


